In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/kaggle/input/datasets/lakshminarayana24/ames-housing-dataset/AmesHousing.csv")
df.head().T

                        0          1          2          3          4
Order                   1          2          3          4          5
PID             526301100  526350040  526351010  526353030  527105010
MS SubClass            20         20         20         20         60
MS Zoning              RL         RH         RL         RL         RL
Lot Frontage        141.0       80.0       81.0       93.0       74.0
...                   ...        ...        ...        ...        ...
Mo Sold                 5          6          6          4          3
Yr Sold              2010       2010       2010       2010       2010
Sale Type             WD         WD         WD         WD         WD
Sale Condition     Normal     Normal     Normal     Normal     Normal
SalePrice          215000     105000     172000     244000     189900

[82 rows x 5 columns]

1.Understandind data

In [3]:
df.shape

(2930, 82)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [5]:
df['Lot Area'].nunique()

1960

In [6]:
df.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [7]:
#df.columns

## Data Preprocessing

In [8]:
df = df.drop(['Pool QC','Fence','Misc Feature','Alley','Order','PID'], axis = 1)

In [9]:
df['SalePrice'] = np.log1p(df['SalePrice'])

In [10]:
df.shape

(2930, 76)

In [11]:
df.isna().sum()

MS SubClass         0
MS Zoning           0
Lot Frontage      490
Lot Area            0
Street              0
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 76, dtype: int64

In [12]:
# Checking numeric columns to fill the columns with Mean or Median 

print(df['Garage Yr Blt'].mean())   
print(df['Garage Yr Blt'].median())  

print(df['Lot Frontage'].mean())
print(df['Lot Frontage'].median())

1978.1324431613136
1979.0
69.22459016393442
68.0

In [13]:
num_cols = df.select_dtypes(['int64','float64']).columns

In [14]:
num_cols.shape

(37,)

In [15]:
# Filling missing num_cols with mean

for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

In [16]:
num_cols.isna().sum()

np.int64(0)

In [17]:
num_cols.shape

(37,)

In [18]:
cat_cols = df.select_dtypes(include = ['object']).columns

for col in cat_cols:
    missing_percent = (
        df[col].isna().sum()
    )*100

    if missing_percent > 40:
        df[col] = df[col].fillna('None')
    else:
        df[col] = df[col].fillna(df[col].mode()[0])

In [19]:
df[cat_cols] = df[cat_cols].astype('category')

In [20]:
cat_cols.shape

(39,)

## EDA

In [21]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(
    drop = 'first',
    sparse_output = False,
    dtype = int
)
one_hot_encoded = ohe.fit_transform(df[cat_cols])

In [22]:
one_hot_encoded.shape

(2930, 225)

In [23]:
encoded_df = pd.DataFrame(
    one_hot_encoded,
    columns=ohe.get_feature_names_out(cat_cols)
)

print(encoded_df.head())

   MS Zoning_C (all)  MS Zoning_FV  MS Zoning_I (all)  MS Zoning_RH  \
0                  0             0                  0             0
1                  0             0                  0             1
2                  0             0                  0             0
3                  0             0                  0             0
4                  0             0                  0             0

   MS Zoning_RL  MS Zoning_RM  Street_Pave  Lot Shape_IR2  Lot Shape_IR3  \
0             1             0            1              0              0
1             0             0            1              0              0
2             1             0            1              0              0
3             1             0            1              0              0
4             1             0            1              0              0

   Lot Shape_Reg  ...  Sale Type_ConLw  Sale Type_New  Sale Type_Oth  \
0              0  ...                0              0              0
1              1  ...                0              0              0
2              0  ...                0              0              0
3              1  ...                0              0              0
4              0  ...                0              0              0

   Sale Type_VWD  Sale Type_WD   Sale Condition_AdjLand  \
0              0              1                       0
1              0              1                       0
2              0              1                       0
3              0              1                       0
4              0              1                       0

   Sale Condition_Alloca  Sale Condition_Family  Sale Condition_Normal  \
0                      0                      0                      1
1                      0                      0                      1
2                      0                      0                      1
3                      0                      0                      1
4                      0                      0                      1

   Sale Condition_Partial
0                       0
1                       0
2                       0
3                       0
4                       0

[5 rows x 225 columns]

Recursive Method For Feature Selection

In [24]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [25]:
num_df = df.select_dtypes(include = ['int64','float64'])

In [26]:
final_df = pd.concat(
    [num_df, encoded_df],
    axis=1
)

In [27]:
final_df.shape

(2930, 262)

In [28]:
X = final_df.drop(['SalePrice'] , axis = 1)

In [29]:
y = final_df['SalePrice']

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

In [31]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

estimator = LinearRegression()

In [32]:
rfe = RFE(
    estimator = estimator,
    n_features_to_select = 100
)

In [33]:
X_train.shape

X_test.shape

y_train.shape

y_test.shape

(586,)

In [34]:
X_train_rfe = rfe.fit_transform(X_train, y_train) 

X_test_rfe = rfe.transform(X_test)

In [35]:
selected_features = X.columns[rfe.support_]

print(selected_features)

Index(['Overall Qual', 'Full Bath', 'Fireplaces', 'Garage Cars',
       'MS Zoning_C (all)', 'MS Zoning_FV', 'MS Zoning_RH', 'MS Zoning_RL',
       'MS Zoning_RM', 'Street_Pave', 'Lot Shape_IR2', 'Lot Shape_IR3',
       'Utilities_NoSeWa', 'Utilities_NoSewr', 'Neighborhood_ClearCr',
       'Neighborhood_Crawfor', 'Neighborhood_GrnHill', 'Neighborhood_Landmrk',
       'Neighborhood_MeadowV', 'Neighborhood_NoRidge', 'Neighborhood_NridgHt',
       'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Veenker',
       'Condition 1_Norm', 'Condition 1_PosA', 'Condition 1_PosN',
       'Condition 2_Feedr', 'Condition 2_Norm', 'Condition 2_PosN',
       'Condition 2_RRNn', 'Bldg Type_Twnhs', 'Bldg Type_TwnhsE',
       'House Style_2.5Unf', 'Roof Style_Gable', 'Roof Style_Gambrel',
       'Roof Style_Hip', 'Roof Style_Mansard', 'Roof Style_Shed',
       'Roof Matl_CompShg', 'Roof Matl_Membran', 'Roof Matl_Metal',
       'Roof Matl_Roll', 'Roof Matl_Tar&Grv', 'Roof Matl_WdShake',
       'Roof Matl_WdShngl', 'Exterior 1st_BrkComm', 'Exterior 1st_BrkFace',
       'Exterior 1st_CBlock', 'Exterior 1st_ImStucc', 'Exterior 1st_PreCast',
       'Exterior 1st_Stone', 'Exterior 2nd_AsphShn', 'Exterior 2nd_CBlock',
       'Exterior 2nd_CmentBd', 'Exterior 2nd_PreCast', 'Exter Cond_Fa',
       'Exter Cond_Po', 'Foundation_CBlock', 'Foundation_PConc',
       'Foundation_Stone', 'Foundation_Wood', 'Bsmt Qual_Fa', 'Bsmt Qual_Gd',
       'Bsmt Qual_Po', 'Bsmt Qual_TA', 'Bsmt Cond_Fa', 'Bsmt Cond_Gd',
       'Bsmt Cond_None', 'Bsmt Cond_Po', 'Bsmt Cond_TA', 'Bsmt Exposure_Gd',
       'BsmtFin Type 1_Unf', 'Heating_GasW', 'Heating_Grav', 'Heating QC_Po',
       'Central Air_Y', 'Kitchen Qual_Fa', 'Kitchen Qual_Gd',
       'Kitchen Qual_TA', 'Functional_Maj2', 'Functional_Min1',
       'Functional_Min2', 'Functional_Mod', 'Functional_Sal', 'Functional_Sev',
       'Functional_Typ', 'Garage Qual_Fa', 'Garage Qual_Gd', 'Garage Qual_Po',
       'Garage Qual_TA', 'Garage Cond_Fa', 'Garage Cond_Gd', 'Garage Cond_Po',
       'Garage Cond_TA', 'Sale Type_ConLI', 'Sale Condition_AdjLand',
       'Sale Condition_Alloca', 'Sale Condition_Normal',
       'Sale Condition_Partial'],
      dtype='object')

In [36]:
from xgboost import XGBRegressor

In [37]:
xgb = XGBRegressor(
    n_estimators = 350,
    learning_rate = 0.024515891601486938,
    max_depth = 5,
    random_state = 42
)

In [38]:
xgb.fit(X_train_rfe, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.024515891601486938, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=350, n_jobs=None,
             num_parallel_tree=None, ...)

In [39]:
y_pred = xgb.predict(X_test_rfe)

In [40]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)

R2 Score: 0.8694394955600477

In [41]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

n = X_test.shape[0]   # number of rows
p = X_test.shape[1]   # number of features

adjusted_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)

print("Adjusted R2:", adjusted_r2)

Adjusted R2: 0.7642657558723084

In [42]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("MAE Error", mae)

MAE Error 0.11450350655396938

In [43]:
mean_target = np.mean(pd.concat([y_train , y_test]))

In [44]:
MAE_per = (mae/mean_target)*100
print("MAE Percentage = ",MAE_per)

MAE Percentage =  0.952530923793857

In [45]:
from sklearn.metrics import mean_squared_error
rmsr = np.sqrt(mean_squared_error(y_test , y_pred))
print(rmsr)

0.1554268843601775

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Price")

plt.ylabel("Predicted Price")

plt.title("Actual vs Predicted")

plt.show()